current_version = "0.3.0"

[[files]]
path = "CHANGELOG.md"
search = "# Changelogs"
replace = """
# Changelogs

## {{new_version}}

Date: {{nowFormat.dateISO}} - Asia/Tokyo

"""

[[files]]
path = "package.json"
search = "\"version\": \"{{current_version}}\","
replace = "\"version\": \"{{new_version}}\","
