# -----------------
# Taskfile for workspace-configs itself.
# -----------------
version: '3'

tasks:
  setup:
    description: 'Setup workspace for development'
    cmds:
      - 'bun install'
      - 'lefthook install'
  verify:
    description: 'Health check all files'
    cmds:
      - 'lefthook run pre-commit --all-files'
      - 'bun x renovate-config-validator renovate/*'
  dry-run:
    description: 'Dry run Renovate.'
    env:
      RENOVATE_CONFIG_FILE: './renovate.json5'
      RENOVATE_TOKEN:
        sh: 'gh auth token'
    vars:
      repo_name: '{{ default "attakei/workspace-configs" .CLI_ARGS }}'
    cmds:
      - 'bun x renovate --dry-run --schedule= --require-config=ignored {{.repo_name}}'
  release-*:
    desc: 'Run release process'
    vars:
      LEVEL: '{{index .MATCH 0}}'
    cmds:
      - 'age {{.LEVEL}}'
